on:
  push:
    branches:
      - main
  workflow_dispatch:

name: pack

jobs:
  pack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: SSH Agent
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      - name: Download
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          git clone --recurse-submodules --depth 1 --shallow-submodules git@github.com:CoLearn-Dev/colink-server-dev.git
          git clone --recurse-submodules --depth 1 --shallow-submodules git@github.com:CoLearn-Dev/colink-sdk-a-rust-dev.git
          git clone --recurse-submodules --depth 1 --shallow-submodules git@github.com:CoLearn-Dev/colink-sdk-p-rust-dev.git
          git clone --recurse-submodules --depth 1 --shallow-submodules git@github.com:CoLearn-Dev/colink-protocol-policy-module-dev.git
          git clone --recurse-submodules --depth 1 --shallow-submodules git@github.com:CoLearn-Dev/colink-protocol-remote-storage-dev.git
      - name: Pack
        run: |
          tar -pcf colink.tar colinkctl colink-*
          cat colink.tar >> install_colink.sh
      - name: Get RELEASE_NAME
        run: |
          echo "RELEASE_NAME=$(date +'%Y-%m-%d')-$(expr $(date +%s) - $(date +%s -d "$(date +'%Y-%m-%d')"))" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: install_colink.sh
          path: install_colink.sh
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: $RELEASE_NAME
          body: $RELEASE_NAME
          draft: false
          prerelease: false
